### ISSUE TITLE
Etiquetas mal cerradas o sin cerrar

### ISSUE THREAD

**Issue by oneeyedman** [Adalab/c-s1-lascodebreakers#1]
Buenas, quizás el principal "fallo" es que hay etiquetas de cierre duplicadas, etiquetas sin cerrar y etiquetas cerradas con otras (hay un `<h4>` cerrado con un `</h3>`.

Dadle una vuelta y tirad sin problema del [validador de la W3C](https://validator.w3.org/#validate_by_input) para revisar ;)

**Comment by MartaAS** [comment]
hecho!

**Comment by oneeyedman** [comment]
Todavía saltan algunos errores por elementos no cerrados al pasar el validador. Solucionar estas cosas es una tarea ardua, ánimo!

**Comment by crisgalasanchez** [comment]
listo! que práctico es el validador !!!!

**Comment by oneeyedman** [comment]
Excelente!
