### ISSUE TITLE
Prefijo de css mal aplicado

### ISSUE THREAD

**Issue by oneeyedman** [Adalab/c-s1-lascodebreakers#4]
🤯 Oh no!

Al aplicar el prefijo de webkit para la propiedad transform se os ha pasado el - inicial.
Debería ser: -webkit-transform: scale(1.3);

Pero tengo una pregunta extra: realmente lo necesitáis?
(imaginad a continuación el gif ese famoso del hamster que te mira de repente)

**Comment by crisgalasanchez** [comment]
solucionado!

**Comment by oneeyedman** [comment]
Reabro el issue porque sigo viendo el prefijo mal aplicado. A por ellos!

**Comment by crisgalasanchez** [comment]
ahora ? es que se nos habia escapado los situados en el footer
yo tengo otra pregunta hacia tu pregunta, si no lo ponemos no haria el efecto de agrandarse al posicionarse encima, habria otra manera de hacerlo?

**Comment by crisgalasanchez** [comment]
he resuelto mi propia pregunta 
solucionado: he omitido la etiqueta!
y.......... FUNCIONA!

**Comment by oneeyedman** [comment]
Nice!
